### ISSUE TITLE
can not find compatible vulkan driver

### ISSUE THREAD

**Issue by biubiubiu919** [guardstrikelab/carla_apollo_bridge#58]
follow the guide of Getting Started, when execute the “cd carla_apollo_bridge/scripts
./docker_run_carla.sh” command in terminater，the program stop and pop out “can not find compatible vulkan driver”

**Comment by charles-lei** [comment]
could you run Carla with this?
`docker run -it --privileged --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw  carlasim/carla:0.9.13 ./CarlaUE4.sh`

**Comment by biubiubiu919** [comment]
yes, i can run this command to start carla.But when i  use docker compose file to run carla will encounter the driver problem.

**Comment by charles-lei** [comment]
> yes, i can run this command to start carla.But when i use docker compose file to run carla will encounter the driver problem.

Please help to try if it works:
```
version: '3.7'
services:
    simulator:
        image: carlasim/carla:0.9.13
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        privileged: true
        environment:
          SDL_VIDEODRIVER: x11
          DISPLAY: $DISPLAY
        ports:
            - "2000:2000"
            - "2001:2001"
            - "2002:2002"

        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: ["gpu"]

        command: ./CarlaUE4.sh  -quality-level=Low -carla-rpc-port=2000
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone
        restart: always
```
